import baseApi from "@/redux/api/baseApi";

export const balanceApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    addBalance: builder.mutation({
      query: (balanceData) => {
        return {
          url: "/payment/add-balance",
          method: "POST",
          body: balanceData,
        };
      },
    }),
  }),
});

// Hooks generated by RTK Query for our endpoints
export const { useAddBalanceMutation } = balanceApi;
