import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
import { Poppins } from "next/font/google";
import "./globals.css";

import ThemeProvider from "@/lib/ThemeProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Peared",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${poppins.className} antialiased bg-white `}>
        <Navbar />

        <AntdRegistry>
          <ThemeProvider>
            <div className="py-2 md:py-12">{children}</div>
          </ThemeProvider>
        </AntdRegistry>

        <Footer />
      </body>
    </html>
  );
}
