import baseApi from "@/redux/api/baseApi";

export const feedbackApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    // add feedback
    feedbackProvider: builder.mutation({
      query: (feedbackData) => {
        return {
          url: "/provider/create-provider-feedBack",
          method: "POST",
          body: feedbackData,
        };
      },
      invalidatesTags: ["feedback"],
    }),
    reportProvider: builder.mutation({
      query: (reportData) => {
        return {
          url: "/provider/report-provider",
          method: "POST",
          body: reportData,
        };
      },
      invalidatesTags: ["feedback"],
    }),

    // allProjects: builder.query({
    //   query: () => {
    //     return {
    //       url: "/project/my-all-project",
    //       method: "GET",
    //     };
    //   },
    // }),
  }),
});

// Hooks generated by RTK Query for our endpoints
export const { useFeedbackProviderMutation, useReportProviderMutation } =
  feedbackApi;
