import baseApi from "@/redux/api/baseApi";

export const feedbackApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    // contact us
    contactUs: builder.mutation({
      query: (contactData) => {
        return {
          url: "/contact/create-contact",
          method: "POST",
          body: contactData,
        };
      },
      invalidatesTags: ["feedback"],
    }),
    // add feedback
    feedbackProvider: builder.mutation({
      query: (feedbackData) => {
        return {
          url: "/provider/create-provider-feedBack",
          method: "POST",
          body: feedbackData,
        };
      },
      invalidatesTags: ["feedback"],
    }),
    reportProvider: builder.mutation({
      query: (reportData) => {
        return {
          url: "/report/create-report",
          method: "POST",
          body: reportData,
        };
      },
      invalidatesTags: ["feedback"],
    }),

    // allProjects: builder.query({
    //   query: () => {
    //     return {
    //       url: "/project/my-all-project",
    //       method: "GET",
    //     };
    //   },
    // }),
  }),
});

// Hooks generated by RTK Query for our endpoints
export const {
  useContactUsMutation,
  useFeedbackProviderMutation,
  useReportProviderMutation,
} = feedbackApi;
