import { baseApi } from "../api/baseApi";

export const userApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    // Example: Fetch currently logged-in user's data
    getUserData: builder.query({
      query: (token) => ({
        url: "/user/my-profile",
        method: "GET",
        headers: {
          Authorization: `Bearer ${token}`,
        },
      }),
    }),

    // Example: Update user data
    updateUserData: builder.mutation({
      query: (data) => ({
        url: "/user/update",
        method: "PATCH",
        body: data,
      }),
    }),
  }),
});

// Hooks generated by RTK Query for our endpoints
export const { useGetUserDataQuery, useUpdateUserDataMutation } = userApi;
