import { baseApi } from "../api/baseApi";

export const userApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    // Example: Fetch currently logged-in user's data
    getUserData: builder.query({
      query: () => ({
        url: "/user/my-profile",
        method: "GET",
      }),
      providesTags: ["a"],
    }),

    // Example: Update user data
    updateUserData: builder.mutation({
      query: (data) => ({
        url: "/user/update",
        method: "POST",
        body: data,
      }),
      invalidatesTags: ["a"],
    }),
  }),
});

// Hooks generated by RTK Query for our endpoints
export const { useGetUserDataQuery, useUpdateUserDataMutation } = userApi;
