import baseApi from "@/redux/api/baseApi";

export const projectApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    // add project for users
    addProject: builder.mutation({
      query: (projectData) => {
        return {
          url: "/project/create-project",
          method: "POST",
          body: projectData,
        };
      },
    }),

    myProjects: builder.query({
      query: () => {
        return {
          url: "/project/my-project",
          method: "GET",
        };
      },
    }),
    myProjectBits: builder.query({
      query: (id) => {
        return {
          url: `/project/bit-project/${id}`,
          method: "GET",
        };
      },
    }),
    myProjectBitDetails: builder.query({
      query: (id) => {
        return {
          url: `/bit/single-project/${id}`,
          method: "GET",
        };
      },
    }),
  }),
});

// Hooks generated by RTK Query for our endpoints
export const {
  useAddProjectMutation,
  useMyProjectsQuery,
  useMyProjectBitsQuery,
  useMyProjectBitDetailsQuery,
} = projectApi;
