import baseApi from "@/redux/api/baseApi";

export const projectApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    // add project for users
    addProject: builder.mutation({
      query: (projectData) => {
        return {
          url: "/project/create-project",
          method: "POST",
          body: projectData,
        };
      },
    }),

    myProjects: builder.query({
      query: () => {
        return {
          url: "/project/my-project",
          method: "GET",
        };
      },
    }),
  }),
});

// Hooks generated by RTK Query for our endpoints
export const { useAddProjectMutation, useMyProjectsQuery } = projectApi;
